<p align="center"><u><strong>Terms of Use</strong></u></p>

<p>Thank you for using the Easy Landing Page Creator website (accessible at: http://easylandingpagecreator.com hereinafter, the &quot;Website&quot;). This page states the terms and conditions (&quot;Terms of Use&quot;) under which you may use the Website and any materials, online communications and other information that is or becomes available on the Website. By accessing the Website you accept and agree to be bound, without limitation or qualification by these terms and conditions. If you do not accept any of the terms or conditions stated here, do not use the Website.</p>

<p><strong><u>Agreement Between You &amp; Easy Landing Page Creator</u></strong><br />
  The Website is owned and operated by Matrix Systems Ltd., a corporation located in British Anguilla (hereinafter &quot;ELPC&quot;) and is offered to you conditioned on your acceptance without modification of the terms, conditions, disclaimers and notices contained herein. Use of the content, services, and/or products presented in any or all areas of this site constitutes your agreement that you will not use the Website for any unlawful purpose and that you will abide by these Terms of Use and those posted in specific areas of the site. In addition, when using particular ELPC owned or operated services, you shall be subject to any posted guidelines or rules applicable to such services, which may be posted and modified from time to time. All such guidelines or rules (including but not limited to our Spam Policy) are hereby incorporated by reference into these Terms of Use.</p>

<p>This agreement between you and ELPC is effective until terminated by ELPC, and may be terminated by ELPC at any time. Please note that ELPC reserves the right to change the Terms of Use under which this Website and its offerings are extended to you. Any such change shall be effective upon notice, which may be given by ELPC posting such change on the Website, by e-mail, or any other reasonable way. All modifications to this Terms of Use webpage shall be deemed a posting for purposes of notice. If a change is notified by a posting on the Website, it shall be deemed to take effect when posted; if a change is notified by e-mail, it shall be deemed to take effect when the e-mail is sent; and if a modification is notified in any other way, it shall be deemed to take effect when the relevant notice is sent or issued by or on behalf of ELPC. Your continued use of the Website following notice of such modifications will be conclusively deemed acceptance of any changes to these Terms of Use. You agree that notice of changes to these Terms of Use on the Website, by posting, such as modification of this Terms of Use webpage, or delivered by email, or provided in any other reasonable way constitutes reasonable and sufficient notice.</p>

<p><strong><u>Collection &amp; Use of Information by ELPC</u></strong><br />
  ELPC collects personal information when you use ELPC products or services, when you register with ELPC, and when you visit ELPC web pages or the web pages of ELPC partners. ELPC may combine the information that we have with information we obtain from business partners or other companies.</p>

<p><strong><u>Cyprus Law and Venue</u></strong><br />
  These Terms of Use will be interpreted and governed by the domestic laws of Cyprus, without giving effect to any choice of law or conflict of law provision or rule that would cause the application of the laws of any jurisdiction other than Cyprus. By using this Website you expressly agree, acknowledge and consent to personal jurisdiction in Cyprus and that venue for any dispute between you and ELPC relating to your use of the Website, the Terms of Use, or any other dispute relating to the Website shall be exclusively in the state and federal courts located in Nicosia, Cyprus.</p>

<p><strong><u>Restrictions</u></strong><br />
  ELPC expends significant time and expense gathering, preparing, compiling, and developing the data and other information and content provided on the ELPC Website. Consequently, data scraping, website scraping, screen scraping, and all other forms of automated and/or manual data and content mining are expressly prohibited and you agree not use any of the data, information, or content on the Website except as expressly permitted by these Terms of Use. You further warrant that you will not attempt or actually systematically extract data contained in this Website to populate databases for internal or external use.</p>

<p><strong><u>License</u></strong><br />
  These Terms of Use provide you with a personal, revocable, nonexclusive, nontransferable license to use this Website conditioned on your continued compliance with these Terms of Use. You may print and download materials and information on this Website solely for personal and noncommercial use; provided that in all cases all hard copies contain all copyright and other applicable notices contained in such materials and information. Notwithstanding the foregoing and except as otherwise expressly permitted herein, you may not modify, copy, distribute, broadcast, transmit, reproduce, publish, license, transfer, sell, scrape, mirror, frame, or otherwise use any information or material obtained from or through this Website.</p>

<p>You represent that you are of legal age to form a binding contract and are not a person barred from using or receiving any ELPC services under the laws of the United States or any other applicable jurisdiction. You also warrant to ELPC that you will not use this Website for any purpose that is unlawful, prohibited by any applicable regulation or is otherwise inconsistent with these Terms of Use, including, without limitation, defamation, disparagement, harassment, invasion of privacy, obscenity, or copyright or trademark infringement. Furthermore, recognizing the global nature of the Internet, you agree to comply with all local rules regarding online conduct and acceptable Content.</p>

<p>COMMERCIAL USE: Commercial use of this Website is only available to paid subscribers of ELPC services under a separate Terms of Use license.</p>

<p><strong><u>Content</u></strong><br />
  This Website contains data, information, and other materials and content (&quot;Content&quot;) created and/or compiled by ELPC or by third parties. Some of the data and information is obtained from public and other third party sources. Whie we believe that these sources are generally reliable, we have no duty to pre-screen such Content and are not responsible for any failure or delay in removing such Content. ELPC makes no representation or warranty as to the reliability, accuracy, completeness or authenticity of any information contained in the Website. You agree that you must evaluate, and bear all risks associated with, the use of any Content, (including risks relating to the infringement or potential infringement of third party intellectual property rights), that you may not rely on said Content, and that under no circumstances will ELPC be liable in any way for any Content or for any loss or damage of any kind incurred as a result of the use of any Content on the Website or obtained through the Website.</p>

<p><strong><u>Backlinks</u></strong><br />
  ELPC is dedicated to preserving the quality of all easylandingpagecreator.com web properties. You agree to comply with Google&#39;s policies and guidelines regarding link building. ELPC reserves the right to remove any pages that violate Google&rsquo;s Link Schemes Quality Guidelines.</p>

<p><strong><u>Cookies</u></strong><br />
  This Website may use &quot;cookies,&quot; Flash objects or similar electronic tools to collect information, such as the IP address of your computer, to enhance and customize your experience with this Website. A cookie is a small text file that is placed on your computer and which collects information about your use of this Website, such as the web pages visited, the date and the time of a visit, the web sites you visited immediately before, etc. By using this Website you agree to placement of cookies on your computer. Of course, you may choose not to accept any cookies from any party by changing the settings on your browser. However, if you set your browser to refuse cookies, some portions of our Website may not function properly.</p>

<p><strong><u>COPYRIGHT COMPLAINTS</u></strong><br />
  ELPC respects the intellectual property of others. It is ELPC &#39;s policy to respond expeditiously to claims of copyright and other intellectual property infringement. ELPC will promptly process and investigate notices of alleged infringement and will take appropriate actions under the Digital Millennium Copyright Act (&quot;DMCA&quot;) and other applicable intellectual property laws. Upon receipt of notices complying or substantially complying with the DMCA, ELPC may act expeditiously to remove or disable access to any material claimed to be infringing or claimed to be the subject of infringing activity and may act expeditiously to remove or disable access to any reference or link to material or activity that is claimed to be infringing. ELPC will terminate access for subscribers and account holders who are repeat infringers.</p>

<p><strong><u>Notifying ELPC of Copyright Infringement:</u></strong><br />
  To provide ELPC notice of an infringement, you must provide a written communication to the attention of &quot;DMCA Infringement Notification Dept.&quot; care of teamzukul@gmail.com that sets forth the information specified by the&nbsp;<a href="http://www.copyright.gov/title17/92chap5.html#512">DMCA</a>. Please note that we may post your notification, with personally identifiable information redacted, to a clearinghouse such as chillingeffects.org. Please also note that you may be liable for damages (including costs and attorneys&#39; fees) if you materially misrepresent that an activity is infringing your copyright.</p>

<p><strong><u>Providing ELPC with Counter-Notification:</u></strong><br />
  If we remove or disable access to content in response to an infringement notice, we will make reasonable attempts to contact the owner or administrator of the affected site or content. If you feel that your material does not constitute infringement, you may provide ELPC with a counter notification by written communication to the attention of &quot;DMCA Counter Notification Dept.&quot; at teamzukul@gmail.com that sets forth all of the necessary information required by the&nbsp;<a href="http://www.copyright.gov/title17/92chap5.html#512">DMCA</a>. Please note that you may be liable for damages (including costs and attorneys&#39; fees) if you materially misrepresent that an activity is not infringing the copyrights of others. If you are uncertain whether an activity constitutes infringement, we recommended seeking advice of an attorney.</p>

<p><strong><u>Privacy</u></strong><br />
  ELPC may gather certain personal information about you relevant to the purposes of our website. ELPC&rsquo;s privacy policy explains how ELPC treats your personal information, and protects your privacy, when you use our Website and related services. Through your use of this Website or of any of our related services, you consent to the collection and use (as set forth in ELPC&#39;s privacy policy) of such personal information, including the transfer of this information to the United States and/or other countries for storage, processing and use by ELPC and its affiliates.</p>

<p>For more detailed information on ELPC&#39;s privacy policy visit our privacy page.</p>

<p><strong><u>Copyright &amp; Ownership</u></strong><br />
  This Website contains Content that is protected by copyright, trademark or other proprietary rights of ELPC or third parties. Content provided by ELPC is copyrighted as a collective work pursuant to applicable copyright law. You agree to comply with any additional copyright notices, information, or restrictions contained in any Content available on or accessed through the Website. Except as expressly permitted by the copyright laws and these Terms of Use, no copying, storage, redistribution or publication of any Content is permitted without the express permission of ELPC, or the owners of such Content or their authorized persons.</p>

<p><strong><u>Indemnity</u></strong><br />
  You agree to indemnify and hold ELPC, its parent, subsidiaries, affiliates, successors, assigns, owners, directors, officers, employees, agents, service providers, and suppliers harmless from any claim or demand, including reasonable attorney fees and court costs, made by any third party due to or arising out of your use of the Website, your violation of the Terms of Use, your breach of any of the representations and warranties herein, or your violation of any third party rights.</p>

<p><strong><u>DISCLAIMER OF WARRANTY</u></strong><br />
  YOU ACKNOWLEDGE AND AGREE THAT USE OF THE WEBSITE AND ITS CONTENT IS ENTIRELY AT YOUR OWN RISK. ALL MATERIALS AND CONTENT IN THIS WEBSITE, INCLUDING THOSE PROVIDED BY LINKS TO THIRD-PARTY WEB SITES ARE PROVIDED &quot;AS IS&quot; WITHOUT WARRANTY OF ANY KIND. THE CONTENT PUBLISHED ON THIS WEBSITE MAY INCLUDE INACCURACIES. ELPC MAKES NO REPRESENTATIONS AND, TO THE FULLEST EXTENT ALLOWED BY LAW, DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO WARRANTIES OF NON-INFRINGEMENT OF INTELLECTUAL PROPERTY OR OTHER PROPRIETARY RIGHTS, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR REGARDING THE SUITABILITY OF THE INFORMATION OR CONTENT. FURTHERMORE, ELPC MAKES NO REPRESENTATIONS AND, TO THE FULLEST EXTENT ALLOWED BY LAW, DISCLAIMS ALL WARRANTIES REGARDING THE ACCURACY, RELIABILITY, COMPLETENESS OR TIMELINESS OF THE CONTENT, SERVICES, PRODUCTS, TEXT, GRAPHICS, LINKS, OR OTHER ITEMS CONTAINED WITHIN THE WEBSITE, OR THE RESULTS OBTAINED FROM ACCESSING AND USING THIS WEBSITE AND/OR THE CONTENT CONTAINED HEREIN. ELPC DOES NOT WARRANT THAT THE WEBSITE AND ITS CONTENT, INCLUDING THE SERVER(S) THAT MAKES THEM AVAILABLE, ARE FREE OF VIRUSES, MALWARE, OR OTHER HARMFUL COMPONENTS. These disclaimers of implied warranties are not permitted in some jurisdictions and consequently the foregoing disclaimers may not apply to you in such jurisdictions.</p>

<p><strong><u>LIMITATION ON LIABILITY</u></strong><br />
  UNDER NO CIRCUMSTANCES SHALL ELPC BE LIABLE FOR DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES (EVEN IF ELPC HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM ANY ASPECT OF YOUR USE OF THE WEBSITE, WHETHER THE DAMAGES ARISE FROM USE OR MISUSE OF THE WEBSITE, FROM INABILITY TO USE THE WEBSITE, OR THE INTERRUPTION, SUSPENSION, MODIFICATION, ALTERATION, OR TERMINATION OF THE WEBSITE. SUCH LIMITATION SHALL ALSO APPLY WITH RESPECT TO DAMAGES INCURRED BY REASON OF ANY SERVICES OR PRODUCTS RECEIVED THROUGH OR ADVERTISED IN CONNECTION WITH THE WEBSITE OR ANY LINKS ON THE WEBSITE, AS WELL AS BY REASON OF ANY INFORMATION OR ADVICE RECEIVED THROUGH OR ADVERTISED IN CONNECTION WITH THE WEBSITE OR ANY LINKS ON THE WEBSITE. THESE LIMITATIONS SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW. These liability limitations are not permitted in some jurisdictions and consequently the foregoing limitations may not apply to you in such jurisdictions.</p>
